### ISSUE TITLE
Following the steps. 

### ISSUE THREAD

**Issue by akamzin** [wolterlw/hand_tracking#10]
Can you clarify first two steps. 

1) Now we need to change the BUILD file. Is BUILD file file inside tensorflow/tensorflow?

2) we now are inside tensorflow repo you should remove the @org_tensorflow from dependency paths. Can you provide more information where I need to remove @org_tensorflow?

3) I am getting an error:
fatal error: mediapipe/util/tflite/operations/transpose_conv_bias.h: No such file or directory

**Comment by wyuzyf** [comment]
can you solve this problem? and give me some suggestions? THAMK YOU ~
