### ISSUE TITLE
hands tracking

### ISSUE THREAD

**Issue by faresbs** [wolterlw/hand_tracking#14]
Hi,

I have a dataset of sequences of images (contain right/left hands) and i want to use mediapipe to extract hand regions from these images (both right and left hand or simply the right hand) and then save the hand regions in a destination folder.
I used the hand_tracker script to extract the hands. however, i've noticed that the model sometimes fails to track the same hand. You mentioned here https://github.com/wolterlw/hand_tracking/issues/4#issuecomment-568489055 that hand_tracker2.py supports multiple hands tracking. How can i use that script to keep track of the correct hand (right hand) for a given sequence of frames?
@wolterlw @AmitMY

i appreciate any feedback, thank you.

**Comment by wolterlw** [comment]
Yes, I'm building the tracking pipeline specifically for keeping track of hand ordering. I'll upload it after the holidays.

**Comment by wolterlw** [comment]
check out the `multihand` branch

**Comment by faresbs** [comment]
I am using the multihand tracker in which i am passing the current image of the sequence with hand detections of the previous frame: 
for image in image_sequence:
hands = HandTracker(image, prev_hands)

but it is failing to accurately track the hand (See pictures)
![images0002](https://user-images.githubusercontent.com/18466124/71858106-fe311780-30b7-11ea-88b0-c4e4bd36ff76.png)
![images0013](https://user-images.githubusercontent.com/18466124/71858119-0a1cd980-30b8-11ea-8e41-7c289490b492.png)
