### ISSUE TITLE
3D Pose Estimation

### ISSUE THREAD

**Issue by AmitMY** [wolterlw/hand_tracking#17]
@ahmed-shariff Added support for 3d poses on this code base:
https://github.com/ahmed-shariff/hand_tracking/commit/310fb95caa5f0b9198fdd0157d1ed4ef522069ae

However, using this `hand_tracker.py` 
```python
detector = HandTracker(palm_model_path, landmark_model_path, anchors_path, box_shift=0.2, box_enlarge=1.3)
d = detector(img)
```
With `print(d[0])`, I still am getting the 2D estimation.
@ahmed-shariff mind clarifying?

>        [[457.47368348, 359.82393988],
>        [429.87579848, 298.62916644],
>        [379.11063081, 253.75389192],
>        [317.62233118, 238.91130884],
>        [263.22237604, 230.28409888],
>        [350.34224016, 210.99346312],
>        [283.266783  , 173.77211398],
>        [237.94263826, 172.72647489],
>        [213.60732161, 182.52631797],
>        [342.0273813 , 235.3966395 ],
>        [272.1424833 , 220.17817074],
>        [233.09361395, 237.22693846],
>        [223.68429643, 260.37553656],
>        [342.1249241 , 265.83757083],
>        [281.07808576, 271.40460841],
>        [262.76236076, 303.5830144 ],
>        [266.86327714, 327.15547596],
>        [348.08264754, 291.63407504],
>        [320.50589946, 311.77354425],
>        [316.85192093, 341.60134386],
>        [323.00332217, 360.62679611]]

**Comment by AmitMY** [comment]
I also tried printing the output details for the joints model:
```python
self.interp_joint.get_output_details()
```
Which returned:
> [{'name': 'ld_21_2d', 'index': 893, 'shape': array([ 1, 42], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}, {'name': 'output_handflag', 'index': 894, 'shape': array([1, 1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

Maybe I need to compile these models myself rather than using the already baked tflite models.

**Comment by wolterlw** [comment]
Do you pass [this model](https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark_3d.tflite) to the tracker?

**Comment by AmitMY** [comment]
Oh didn't notice there was a model distinction. Done, and everything seems to work. 
I created a PR for optional 3d support

**Comment by Shahraizz** [comment]
@wolterlw @AmitMY can you help me with this, i am getting this error

> ValueError                                Traceback (most recent call last)
<ipython-input-19-fa2f6ee0a2f7> in <module>
----> 1 kp, box = detector(img)
      2 print(kp)
      3 
      4 f,ax = plt.subplots(1,1, figsize=(10, 10))
      5 

> ~/Desktop/hand_tracking/hand_tracker.py in __call__(self, img)
    184         Mtr = cv2.getAffineTransform(
    185             self._source * scale,
--> 186             self._target_triangle
    187         )
    188 

> ~/Desktop/hand_tracking/hand_tracker.py in predict_joints(self, img_norm)
    106         self.interp_joint.invoke()
    107 
--> 108         joints = self.interp_joint.get_tensor(self.out_idx_joint)
    109         hand_flag = self.interp_joint.get_tensor(self.out_idx_joint_hand_flag)
    110         if len(joints[0]) == 63:

> ValueError: cannot reshape array of size 63 into shape (2)

I tried to run this code:

`landmark_model_path = "./models/hand_landmark_3d.tflite"`
`detector = HandTracker(palm_model_path, landmark_model_path, anchors_path,box_shift=0.2, box_enlarge=1.3)`

After replacing `hand_tracking.py` with this:
ahmed-shariff@310fb95

**Comment by ahmed-shariff** [comment]
I have not been able to work on this for some time, and my fork is a little behind. Did it work if you use only my fork? or perhaps try one of the updates made in this repo?

**Comment by farnaznouraei** [comment]
I am getting the same error as @Shahraizz using the most up-to-date hand-tracker.py version on the repo... Does anyone know how to resolve it?
