### ISSUE TITLE
Removing rotation estimation decreases accuracy 

### ISSUE THREAD

**Issue by AmitMY** [wolterlw/hand_tracking#18]
I used the code in the current master branch to predict the bbox and joints for an image:
![image](https://user-images.githubusercontent.com/5757359/71762465-59a4af00-2ed8-11ea-914a-232ef090b567.png)

Works as well as expected.

Then I used the `hand_tracker2` code in the other branch, which supports multiple hands detection and joints prediction, and got this:
![image](https://user-images.githubusercontent.com/5757359/71762479-8f499800-2ed8-11ea-8c01-0fefbe767045.png)

Notice that the second hand from right (the one detected in both tests) - seems to get better joints prediction when the rotation is predicted.

I'm not sure if there is any other thing going on here, or if this is just a bad, sample size of 1 example, but should be taken into consideration.

Code:
```python
palm_model_path = "./models/palm_detection.tflite"
landmark_model_path = "./models/hand_landmark.tflite"
anchors_path = "data/anchors.csv"

img = cv2.imread('data/hands.jpg')[:, :, ::-1]

# box_shift determines
detector = HandTracker(palm_model_path, landmark_model_path, anchors_path, box_shift=0.2, box_enlarge=1.3)
hands = detector(img)

f, ax = plt.subplots(1, 1, figsize=(10, 10))
ax.imshow(img)
for hand in hands:
    ax.scatter(hand["joints"][:, 0], hand["joints"][:, 1])
    ax.add_patch(Polygon(hand["bbox"], color="#00ff00", fill=False))

f.savefig("data/hands_out.png")
```

**Comment by wolterlw** [comment]
what do you mean "when the rotation is predicted". It's predicted in both cases. which is evident looking at the bounding boxes.
I've changed the anchor selection mechanism a bit to deal with exp overflow, but that's about it.

**Comment by AmitMY** [comment]
Ah I expected the title:
> HAND TRACKER WITHOUT ROTATION ESTIMATION AND JOINT DETECTION

To be without rotation, but you are right, there obviously is rotation.

What do you think is the reason for the rotation to be predicted differently then?
![image](https://user-images.githubusercontent.com/5757359/71768314-c5f5d180-2f1d-11ea-81e1-3e1e4ecfcc11.png)
![image](https://user-images.githubusercontent.com/5757359/71768319-caba8580-2f1d-11ea-8511-67de893e59c8.png)

**Comment by wolterlw** [comment]
So if you look [here](https://github.com/wolterlw/hand_tracking/blob/8fa156b350b4fc9c6e852218c48aea358845bb12/hand_tracker.py#L133), you'll notice that I pick the detection with the largest bounding box.   
In the case of multiple hands I pick the detection [with the largest score ](https://github.com/wolterlw/hand_tracking/blob/17c60dcdb3e7430ded3d5d2339c0997fdf13af3d/hand_tracker2.py#L130).   
Guess the first option worked better for that one hand, but one would have to test the model on some data with compatible ground truth to know which approach works best generally.

**Comment by wolterlw** [comment]
check out the new `multihand` branch. It's a bit cleaner than optical_flow. Accuracy could be better in some cases but I believe it's due to simplistic aggregation.

**Comment by wolterlw** [comment]
I've opened a clean new issue for this problem.
