### ISSUE TITLE
what does the anchor file mean?

### ISSUE THREAD

**Issue by wyp19930313** [wolterlw/hand_tracking#24]
I read the SSD paper, but I still don't understand what the numbers in the anchor file mean. From your code, I know that the first two columns of anchor represent the predicted target center point, but the last two columns are always 1. I don't know what they mean, hope to get your help, thank you

**Comment by wolterlw** [comment]
so as you've read in the SSD paper - anchors are box priors, which means that the whole image area is covered in possible box approximations. During prediction the model infers scores for all those boxes and offsets from each prior box to the actual object bounding box. It's easier to understand visually and the very first [search result](https://www.mathworks.com/help/vision/ug/anchor-boxes-for-object-detection.html) provides a decent explanation.   
Let me know if that makes sense.

**Comment by wyp19930313** [comment]
Thank you for your answer. I know the role of anchor, I looked at your [generated anchor code ](https://gist.github.com/wolterlw/6f1ebc49230506f8e9ce5facc5251d4f)and finally figured it out. Because the anchor's length and width are fixed in your JSON parameters, the last two columns of the anchor file are always 1. When I change to false, I successfully get the correct length and width of the anchor.
