### ISSUE TITLE
How to run the hand_tracker.py

### ISSUE THREAD

**Issue by ila555** [wolterlw/hand_tracking#25]
Hi im a newbie. i tried to run the hand_tracker.py but nothing is happened. i run it in Terminal.

**Comment by wolterlw** [comment]
hand_tracker.py is a module file, you don't run it - you import it.
For examples you can click on the Binder badge I put on top of the README. If you have jupyter installed you can run it on your local machine too.

**Comment by ila555** [comment]
Already able to run. thank you. Is it possible for me to train hand gesture ?
