### ISSUE TITLE
Hand landmark 3D model

### ISSUE THREAD

**Issue by ila555** [wolterlw/hand_tracking#29]
I put in hand_landmark_3d.tflite but got this error instead:

kp_orig = (self._pad1(joints) @ Minv.T)[:,:2]
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

**Comment by wolterlw** [comment]
did you use the 3d landmark fork?

**Comment by ila555** [comment]
what do you mean?

**Comment by wolterlw** [comment]
so this repository does not implement 3d keypoint detection. However there is a fork of the project that supports 3d point regression, you just have to look through the issues and find it.
