### ISSUE TITLE
Where did the `data/anchors.csv` file come from?

### ISSUE THREAD

**Issue by metalwhale** [wolterlw/hand_tracking#3]
Hi @wolterlw, thank you very much for your kind guidance about building _tensorflow_ with custom operations!
May I ask you a question? How did you generate `data/anchors.csv` file? I tried to search around inside the [mediapipe](https://github.com/google/mediapipe/) source code but got nothing.
I'm newbie to the machine learning era so please forgive me if this is a stupid question...

**Comment by wolterlw** [comment]
Hello @metalwhale and don't worry, no questions are stupid!
Regarding yours - I've removed all the mediapipe-related code from `::mediapipe::Status SsdAnchorsCalculator::GenerateAnchors` function in [this calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/ssd_anchors_calculator.cc), left the logic that calculates anchors, took input parameters from the related `.proto` file and passed them in a small C++ program I built to this pure c++ function and wrote generated anchors to a `.csv` file. 
If you're interested - I can provide the code as a gist.

**Comment by metalwhale** [comment]
@wolterlw, thank you for your prompt response!!
Can you provide your code directly inside this awesome repo or somewhere else that can be easily searched? If you do that, people have same question like me will be able to quickly find the right answer!

**Comment by wolterlw** [comment]
@metalwhale updated the README with a link to the script

**Comment by metalwhale** [comment]
@wolterlw Thank you so much!!

**Comment by mlizhardy** [comment]
anchors are now 896 not 2944 https://drive.google.com/file/d/1yiPfkhb4hSbXJZaSq9vDmhz24XVZmxpL/view
https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/palm_detection/palm_detection_gpu.pbtxt

ideas on calculating the new ones?

**Comment by mlizhardy** [comment]
was able to generate them via https://gist.github.com/ogl4jo3/5ba673b61ecc82780299edbcdcca301a
