### ISSUE TITLE
Where are the 21 keypoints?

### ISSUE THREAD

**Issue by rami-alloush** [wolterlw/hand_tracking#30]
Hi,
Thank you for your efforts, I've been looking for something like this.
I'm using MediaPipe multihandtracking to get 42 keypoints for both hands (21 keypoints/hand).
From C++, I'm able to get them and right them to a txt file, but I was hoping to use your code to get these 42 keypoints into python in real time, is this possible?
Thanks 

ref: https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html

**Comment by wolterlw** [comment]
Hello,
it is possible to get the 42 keypoints, but currently this code cannot run in real time as it runs on CPU.
To see a usage example either click the Binder badge or launch `hand_model.ipynb` in your local jupyter environment.
