### ISSUE TITLE
python opencv tensorflow version

### ISSUE THREAD

**Issue by amandazw** [wolterlw/hand_tracking#31]
when I import models, the error shows below:
ValueError: Didn't find custom op for name 'Convolution2DTransposeBias' with version 1
Registration failed

so, I want to know what's the version for the three packages.
Thanks !

**Comment by wolterlw** [comment]
the issue is that you're probably using the wrong .tflite file
the file in mediapipe repo has custom ops. To import these you'd have to compile a custom build of Tensorflow. This is laborious, so I've borrowed a .tflite files from another repo with the custom ops removed. Make sure you use those.
