### ISSUE TITLE
How to reduce false positive?

### ISSUE THREAD

**Issue by edwardnguyen1705** [wolterlw/hand_tracking#32]
Hi, thank you for sharing your code. I have been trying to change the threshold (even to 0.95) to eliminate false positive, buy it did not help.
https://github.com/wolterlw/hand_tracking/blob/0cccb81e620f602e1a8f91aaed525e20b809fdf5/hand_tracker.py#L125

Have anyone had the same situation? Or any suggestion is greatly appreciated.

**Comment by wolterlw** [comment]
I believe the regressor also outputs a confidence score, so you can filter using it as well. This still leaves you with added costs of processing the false positives, but there’s no easy fix for it.
