### ISSUE TITLE
Wht img_norm.shape must be (256,256,3)?

### ISSUE THREAD

**Issue by kukuhaza** [wolterlw/hand_tracking#40]
Hello~ 
Thank you for your work.
In the hand_tracker.py,
I want to enlarge the size and then detect, but I don’t know which parts need to change. Why do you resize to 256,256? If I want to change to other sizes, is it okay?

**Comment by wolterlw** [comment]
This particular neural net expects a (256,256,3) tensor as input. For best quality just crop around the hand region.

**Comment by kukuhaza** [comment]
Thank u for your reply. I will try to crop ,thank you!
