### ISSUE TITLE
MultiHand Detection

### ISSUE THREAD

**Issue by DengHaoke** [wolterlw/hand_tracking#41]
I wonder if it can dectect muti-hands and how many hands could be detected at most?

**Comment by farnaznouraei** [comment]
I think the multihand branch is for that purpose. I tried it and was able to detect 4 hands which was the maximum number present in my videos  
#14

**Comment by wolterlw** [comment]
technically the system should be able to find tens of hands (although [NMS](http://datahacker.rs/deep-learning-non-max-suppression/) might suppress the smaller ones). Keep in mind that each hand, once detected, is processed separately by the joint regressor, so execution time will grow linearly.
