### ISSUE TITLE
I cannot assemble the version TensorFlow for Mac OS

### ISSUE THREAD

**Issue by DmitryRyumin** [wolterlw/hand_tracking#5]
I cannot assemble the version TensorFlow for Mac OS!

It seems I do everything according to the instructions but I get an error on the output

`ValueError: Didn't find custom op for name 'Convolution2DTransposeBias' with version 1`

**1. Step:**

Moved all files from folder **.../mediapipe/util/tflite/operations**  to folder **.../tensorflow/tensorflow/lite/python/custom_ops/**

**2. Step:**

**BUILD** fixed in folder **.../tensorflow/tensorflow/lite/python/custom_ops/**

```
licenses(["notice"])  # Apache 2.0

package(default_visibility = [
    "//visibility:public",
])

cc_library(
    name = "max_pool_argmax",
    srcs = ["max_pool_argmax.cc"],
    hdrs = ["max_pool_argmax.h"],
    deps = [
        "//tensorflow/lite/kernels:kernel_util",
        "//tensorflow/lite/kernels:padding",
        "//tensorflow/lite/kernels/internal:common",
        "//tensorflow/lite/kernels/internal:tensor",
        "//tensorflow/lite/kernels/internal:tensor_utils",
    ],
)

cc_library(
    name = "max_unpooling",
    srcs = ["max_unpooling.cc"],
    hdrs = ["max_unpooling.h"],
    deps = [
        "//tensorflow/lite/kernels:kernel_util",
        "//tensorflow/lite/kernels:padding",
        "//tensorflow/lite/kernels/internal:common",
        "//tensorflow/lite/kernels/internal:tensor",
        "//tensorflow/lite/kernels/internal:tensor_utils",
    ],
)

cc_library(
    name = "transpose_conv_bias",
    srcs = ["transpose_conv_bias.cc"],
    hdrs = ["transpose_conv_bias.h"],
    deps = [
        "//tensorflow/lite/kernels:kernel_util",
        "//tensorflow/lite/kernels:padding",
        "//tensorflow/lite/kernels/internal:tensor",
        "//tensorflow/lite/kernels/internal:tensor_utils",
        "//tensorflow/lite/kernels/internal:types",
    ],
)
```

**3. Step:**

**Configure** the build

`./configure`

**4. Step:**

`bazel build --action_env PATH="$PATH" --noincompatible_strict_action_env --config=opt --incompatible_disable_deprecated_attr_params=false //tensorflow/tools/pip_package:build_pip_package`

**5. Step:**

`./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tensorflow_pkg`

### **Any idea what I'm doing wrong?**

**Comment by DmitryRyumin** [comment]
Problem resolved

**Comment by metalwhale** [comment]
How did you solve that? Can you tell us more in detail?
