### ISSUE TITLE
How can I use hand_tracking with my webcam?

### ISSUE THREAD

**Issue by bogos** [wolterlw/hand_tracking#6]
Hi @wolterlw, thank you very much for this mediapipe wrapper for python!

I have a pretty noob question, I am new to this environment and I would like to use my web cam to use the handtracker, is this possible? You think you could upload a mini example :( I've been trying using videocapture from opencv, but it didn't work for me.

**Comment by wolterlw** [comment]
@bogos I've used OpenCV and it worked like a charm. If you look at [this commit](https://github.com/wolterlw/hand_tracking/blob/7f3894919f68bc6aba2929eed90bdbff818195b1/hand_model.ipynb) that's exactly what I did. Later changed it to be compatible with Binder, where you cannot use a webcam. 
What errors do you get?

**Comment by metalwhale** [comment]
@bogos, you can take a look at my [demo](https://github.com/metalwhale/hand_tracking) which has `anchors.csv` and `hand_tracker.py` file were copied from this repo.
The `README.md` is written in Japanese but all you have to do is just execute these commands:
```
$ pip install opencv-python tensorflow
$ python run.py
```
Btw, I downloaded palm detection model from [here](https://github.com/junhwanjang/mediapipe-models), which works like a charm while using Python API even without custom ops.

**Comment by bogos** [comment]
@metalwhale Thanks! it's just what i was looking for! 🥰🥰
 I have a doubt, it is relatively slow, do you think there is any way to improve this? 😥

@wolterlw the problem apparently was that I had done a bad module installation :( now everything works fine <3

**Comment by bogos** [comment]
@wolterlw the problem apparently was that I had done a bad module installation :( now everything works fine <3 thank you!

**Comment by wolterlw** [comment]
Glad you sorted it out.

**Comment by metalwhale** [comment]
@bogos I don't think it's slow but you can figure it out by comparing to the speed after you _commenting out_ this keypoints-extracting code at `run.py` file in my repo:
```python
points, _ = detector(image)
if points is not None:
    for point in points:
        x, y = point
        cv2.circle(frame, (int(x), int(y)), THICKNESS * 2, POINT_COLOR, THICKNESS)
    for connection in connections:
        x0, y0 = points[connection[0]]
        x1, y1 = points[connection[1]]
        cv2.line(frame, (int(x0), int(y0)), (int(x1), int(y1)), CONNECTION_COLOR, THICKNESS)
```
If it's still slow, I'm pretty sure it's not the fault of hand tracking process...
IMHO we can't do anything else to improve the speed, but you can do a research by yourself.

**Comment by wolterlw** [comment]
Also check out [this new demo](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_desktop.md) in the official Mediapipe repo

**Comment by sebastijan94** [comment]
> @bogos I don't think it's slow but you can figure it out by comparing to the speed after you _commenting out_ this keypoints-extracting code at `run.py` file in my repo:
> 
> ```python
> points, _ = detector(image)
> if points is not None:
>     for point in points:
>         x, y = point
>         cv2.circle(frame, (int(x), int(y)), THICKNESS * 2, POINT_COLOR, THICKNESS)
>     for connection in connections:
>         x0, y0 = points[connection[0]]
>         x1, y1 = points[connection[1]]
>         cv2.line(frame, (int(x0), int(y0)), (int(x1), int(y1)), CONNECTION_COLOR, THICKNESS)
> ```
> 
> If it's still slow, I'm pretty sure it's not the fault of hand tracking process...
> IMHO we can't do anything else to improve the speed, but you can do a research by yourself.

Hi @metalwhale, your example works perfectly, but the FPS is about 5 max. Did you manage to run it at a higher frame rate?

**Comment by ahmed-shariff** [comment]
The implementation here doesn't have the `PreviousLoopbackCalculator` from the graph in https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_desktop.md
I'll try to implement that when I get a chance. For now, I made a [few adjustments](https://github.com/ahmed-shariff/hand_tracking/commit/a1c5aef2a73bb1418e0f47b48e67a5c976537151) to use the previous box(triangle here) to estimate the new jonints. Even though the detections can be a bit jittery, the framerate is pretty good when running on cpu (0.06s per frame when previous box is used).
