### ISSUE TITLE
what's the exact meaning of these two parameters: "box_shift, box_enlarge"

### ISSUE THREAD

**Issue by help8989** [wolterlw/hand_tracking#7]
thanks so much for this python version hand track
when i adjust different values of "box_shift“ and “box_enlarge“, it would affect the effect of hand detection，whether should i adjust these two parameters for different input images? and how to adjust?
thx

**Comment by wolterlw** [comment]
So the thing with the hand detection model is that it detects palms, not hands. This means that we have no idea where the fingers are. Therefore we enlarge the bounding box so it contains the fingers as well. `box_enlarge` parameter is responsible for the new box scale, as compared to the palm bounding box.
Box shift is used to move the box closer to the middle finger base joint as in most cases it is the center of the hand, not the palm center. I do it by adding the (wrist -> middle finger base joint) vector multiplied by `box_shift` to all the box points.
