### ISSUE TITLE
run it on a GPU

### ISSUE THREAD

**Issue by lilyswang** [wolterlw/hand_tracking#8]
Hi,@wolterlw ,thanks for your nice job.  I want to know why  hand_tracker.py don't use the GPUs (I find it only use computer's CPUs).

If I want to use that on a computer with GPU , how should I do ?

Looking forword your reply! Thanks alot.

**Comment by wolterlw** [comment]
I use tflite interpreter to run Mediapipe's models. Currently tflite only supports mobile GPUs so to run the model on a desktop/laptop GPU you'd have to extend tflite with a new "delegate" as they call it, which I believe is far from easy.
I believe it would be possible to use models from [this repository](https://github.com/junhwanjang/mediapipe-models) and run them as a regular tensorflow model on the GPU, but I've only seen this repo recently so didn't have time to validate those models and incorporate them into the pipeline.

**Comment by lilyswang** [comment]
@wolterlw Thanks for your suggestions  ,I will try it .  ^_^

**Comment by wolterlw** [comment]
@lilyswang do you, by any chance have that repo forked or downloaded? because the source was removed by the author.
