### ISSUE TITLE
Inference speed and classification head

### ISSUE THREAD

**Issue by zeenolife** [wolterlw/hand_tracking#9]
I am getting around 2.1 fps on a desktop CPU, which is nowhere around real-time :smile: 
Is this the same for everyone?

Also, in Gooogle AI blog post they said they have gesture classification head, but I can't find it in the code. Can somebody point out where I should look for?

**Comment by VitusMa** [comment]
I have the same performance issues with a CPU.

**Comment by wolterlw** [comment]
regarding fps look at #8 
about the gesture classification head - I did not port it

**Comment by wolterlw** [comment]
also check out the new [desktop hand tracking demo](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_desktop.md) in the official Mediapipe repo
